// Code generated by MockGen. DO NOT EDIT.
// Source: k8s.io/client-go/scale (interfaces: ScalesGetter,ScaleInterface)
//
// Generated by this command:
//
//	mockgen k8s.io/client-go/scale ScalesGetter,ScaleInterface
//

// Package mock_scale is a generated GoMock package.
package mock_scale

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/autoscaling/v1"
	v10 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	scale "k8s.io/client-go/scale"
)

// MockScalesGetter is a mock of ScalesGetter interface.
type MockScalesGetter struct {
	ctrl     *gomock.Controller
	recorder *MockScalesGetterMockRecorder
	isgomock struct{}
}

// MockScalesGetterMockRecorder is the mock recorder for MockScalesGetter.
type MockScalesGetterMockRecorder struct {
	mock *MockScalesGetter
}

// NewMockScalesGetter creates a new mock instance.
func NewMockScalesGetter(ctrl *gomock.Controller) *MockScalesGetter {
	mock := &MockScalesGetter{ctrl: ctrl}
	mock.recorder = &MockScalesGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScalesGetter) EXPECT() *MockScalesGetterMockRecorder {
	return m.recorder
}

// Scales mocks base method.
func (m *MockScalesGetter) Scales(namespace string) scale.ScaleInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scales", namespace)
	ret0, _ := ret[0].(scale.ScaleInterface)
	return ret0
}

// Scales indicates an expected call of Scales.
func (mr *MockScalesGetterMockRecorder) Scales(namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scales", reflect.TypeOf((*MockScalesGetter)(nil).Scales), namespace)
}

// MockScaleInterface is a mock of ScaleInterface interface.
type MockScaleInterface struct {
	ctrl     *gomock.Controller
	recorder *MockScaleInterfaceMockRecorder
	isgomock struct{}
}

// MockScaleInterfaceMockRecorder is the mock recorder for MockScaleInterface.
type MockScaleInterfaceMockRecorder struct {
	mock *MockScaleInterface
}

// NewMockScaleInterface creates a new mock instance.
func NewMockScaleInterface(ctrl *gomock.Controller) *MockScaleInterface {
	mock := &MockScaleInterface{ctrl: ctrl}
	mock.recorder = &MockScaleInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScaleInterface) EXPECT() *MockScaleInterfaceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockScaleInterface) Get(ctx context.Context, resource schema.GroupResource, name string, opts v10.GetOptions) (*v1.Scale, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, resource, name, opts)
	ret0, _ := ret[0].(*v1.Scale)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockScaleInterfaceMockRecorder) Get(ctx, resource, name, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockScaleInterface)(nil).Get), ctx, resource, name, opts)
}

// Patch mocks base method.
func (m *MockScaleInterface) Patch(ctx context.Context, gvr schema.GroupVersionResource, name string, pt types.PatchType, data []byte, opts v10.PatchOptions) (*v1.Scale, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Patch", ctx, gvr, name, pt, data, opts)
	ret0, _ := ret[0].(*v1.Scale)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Patch indicates an expected call of Patch.
func (mr *MockScaleInterfaceMockRecorder) Patch(ctx, gvr, name, pt, data, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Patch", reflect.TypeOf((*MockScaleInterface)(nil).Patch), ctx, gvr, name, pt, data, opts)
}

// Update mocks base method.
func (m *MockScaleInterface) Update(ctx context.Context, resource schema.GroupResource, arg2 *v1.Scale, opts v10.UpdateOptions) (*v1.Scale, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, resource, arg2, opts)
	ret0, _ := ret[0].(*v1.Scale)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockScaleInterfaceMockRecorder) Update(ctx, resource, arg2, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockScaleInterface)(nil).Update), ctx, resource, arg2, opts)
}
