// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: LiiklusService.proto

package liiklus

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest_AutoOffsetReset int32

const (
	SubscribeRequest_EARLIEST SubscribeRequest_AutoOffsetReset = 0
	SubscribeRequest_LATEST   SubscribeRequest_AutoOffsetReset = 1
)

// Enum value maps for SubscribeRequest_AutoOffsetReset.
var (
	SubscribeRequest_AutoOffsetReset_name = map[int32]string{
		0: "EARLIEST",
		1: "LATEST",
	}
	SubscribeRequest_AutoOffsetReset_value = map[string]int32{
		"EARLIEST": 0,
		"LATEST":   1,
	}
)

func (x SubscribeRequest_AutoOffsetReset) Enum() *SubscribeRequest_AutoOffsetReset {
	p := new(SubscribeRequest_AutoOffsetReset)
	*p = x
	return p
}

func (x SubscribeRequest_AutoOffsetReset) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscribeRequest_AutoOffsetReset) Descriptor() protoreflect.EnumDescriptor {
	return file_LiiklusService_proto_enumTypes[0].Descriptor()
}

func (SubscribeRequest_AutoOffsetReset) Type() protoreflect.EnumType {
	return &file_LiiklusService_proto_enumTypes[0]
}

func (x SubscribeRequest_AutoOffsetReset) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscribeRequest_AutoOffsetReset.Descriptor instead.
func (SubscribeRequest_AutoOffsetReset) EnumDescriptor() ([]byte, []int) {
	return file_LiiklusService_proto_rawDescGZIP(), []int{2, 0}
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_LiiklusService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LiiklusService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_LiiklusService_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PublishRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type PublishReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     uint32                 `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishReply) Reset() {
	*x = PublishReply{}
	mi := &file_LiiklusService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReply) ProtoMessage() {}

func (x *PublishReply) ProtoReflect() protoreflect.Message {
	mi := &file_LiiklusService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishReply.ProtoReflect.Descriptor instead.
func (*PublishReply) Descriptor() ([]byte, []int) {
	return file_LiiklusService_proto_rawDescGZIP(), []int{1}
}

func (x *PublishReply) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *PublishReply) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *PublishReply) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type SubscribeRequest struct {
	state           protoimpl.MessageState           `protogen:"open.v1"`
	Topic           string                           `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Group           string                           `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	GroupVersion    uint32                           `protobuf:"varint,4,opt,name=groupVersion,proto3" json:"groupVersion,omitempty"`
	AutoOffsetReset SubscribeRequest_AutoOffsetReset `protobuf:"varint,3,opt,name=autoOffsetReset,proto3,enum=com.github.bsideup.liiklus.SubscribeRequest_AutoOffsetReset" json:"autoOffsetReset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_LiiklusService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LiiklusService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_LiiklusService_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SubscribeRequest) GetGroupVersion() uint32 {
	if x != nil {
		return x.GroupVersion
	}
	return 0
}

func (x *SubscribeRequest) GetAutoOffsetReset() SubscribeRequest_AutoOffsetReset {
	if x != nil {
		return x.AutoOffsetReset
	}
	return SubscribeRequest_EARLIEST
}

type Assignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Partition     uint32                 `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	mi := &file_LiiklusService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_LiiklusService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_LiiklusService_proto_rawDescGZIP(), []int{3}
}

func (x *Assignment) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Assignment) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

type SubscribeReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Reply:
	//
	//	*SubscribeReply_Assignment
	Reply         isSubscribeReply_Reply `protobuf_oneof:"reply"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeReply) Reset() {
	*x = SubscribeReply{}
	mi := &file_LiiklusService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeReply) ProtoMessage() {}

func (x *SubscribeReply) ProtoReflect() protoreflect.Message {
	mi := &file_LiiklusService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeReply.ProtoReflect.Descriptor instead.
func (*SubscribeReply) Descriptor() ([]byte, []int) {
	return file_LiiklusService_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeReply) GetReply() isSubscribeReply_Reply {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *SubscribeReply) GetAssignment() *Assignment {
	if x != nil {
		if x, ok := x.Reply.(*SubscribeReply_Assignment); ok {
			return x.Assignment
		}
	}
	return nil
}

type isSubscribeReply_Reply interface {
	isSubscribeReply_Reply()
}

type SubscribeReply_Assignment struct {
	Assignment *Assignment `protobuf:"bytes,1,opt,name=assignment,proto3,oneof"`
}

func (*SubscribeReply_Assignment) isSubscribeReply_Reply() {}

type AckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in LiiklusService.proto.
	Assignment    *Assignment `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	Topic         string      `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Group         string      `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	GroupVersion  uint32      `protobuf:"varint,5,opt,name=groupVersion,proto3" json:"groupVersion,omitempty"`
	Partition     uint32      `protobuf:"varint,6,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        uint64      `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_LiiklusService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LiiklusService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_LiiklusService_proto_rawDescGZIP(), []int{5}
}

// Deprecated: Marked as deprecated in LiiklusService.proto.
func (x *AckRequest) GetAssignment() *Assignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

func (x *AckRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AckRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *AckRequest) GetGroupVersion() uint32 {
	if x != nil {
		return x.GroupVersion
	}
	return 0
}

func (x *AckRequest) GetPartition() uint32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *AckRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ReceiveRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Assignment      *Assignment            `protobuf:"bytes,1,opt,name=assignment,proto3" json:"assignment,omitempty"`
	LastKnownOffset uint64                 `protobuf:"varint,2,opt,name=lastKnownOffset,proto3" json:"lastKnownOffset,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReceiveRequest) Reset() {
	*x = ReceiveRequest{}
	mi := &file_LiiklusService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveRequest) ProtoMessage() {}

func (x *ReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LiiklusService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveRequest.ProtoReflect.Descriptor instead.
func (*ReceiveRequest) Descriptor() ([]byte, []int) {
	return file_LiiklusService_proto_rawDescGZIP(), []int{6}
}

func (x *ReceiveRequest) GetAssignment() *Assignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

func (x *ReceiveRequest) GetLastKnownOffset() uint64 {
	if x != nil {
		return x.LastKnownOffset
	}
	return 0
}

type ReceiveReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Reply:
	//
	//	*ReceiveReply_Record_
	Reply         isReceiveReply_Reply `protobuf_oneof:"reply"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveReply) Reset() {
	*x = ReceiveReply{}
	mi := &file_LiiklusService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveReply) ProtoMessage() {}

func (x *ReceiveReply) ProtoReflect() protoreflect.Message {
	mi := &file_LiiklusService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveReply.ProtoReflect.Descriptor instead.
func (*ReceiveReply) Descriptor() ([]byte, []int) {
	return file_LiiklusService_proto_rawDescGZIP(), []int{7}
}

func (x *ReceiveReply) GetReply() isReceiveReply_Reply {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *ReceiveReply) GetRecord() *ReceiveReply_Record {
	if x != nil {
		if x, ok := x.Reply.(*ReceiveReply_Record_); ok {
			return x.Record
		}
	}
	return nil
}

type isReceiveReply_Reply interface {
	isReceiveReply_Reply()
}

type ReceiveReply_Record_ struct {
	Record *ReceiveReply_Record `protobuf:"bytes,1,opt,name=record,proto3,oneof"`
}

func (*ReceiveReply_Record_) isReceiveReply_Reply() {}

type GetOffsetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	GroupVersion  uint32                 `protobuf:"varint,3,opt,name=groupVersion,proto3" json:"groupVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffsetsRequest) Reset() {
	*x = GetOffsetsRequest{}
	mi := &file_LiiklusService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffsetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffsetsRequest) ProtoMessage() {}

func (x *GetOffsetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LiiklusService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffsetsRequest.ProtoReflect.Descriptor instead.
func (*GetOffsetsRequest) Descriptor() ([]byte, []int) {
	return file_LiiklusService_proto_rawDescGZIP(), []int{8}
}

func (x *GetOffsetsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *GetOffsetsRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *GetOffsetsRequest) GetGroupVersion() uint32 {
	if x != nil {
		return x.GroupVersion
	}
	return 0
}

type GetOffsetsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offsets       map[uint32]uint64      `protobuf:"bytes,1,rep,name=offsets,proto3" json:"offsets,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffsetsReply) Reset() {
	*x = GetOffsetsReply{}
	mi := &file_LiiklusService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffsetsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffsetsReply) ProtoMessage() {}

func (x *GetOffsetsReply) ProtoReflect() protoreflect.Message {
	mi := &file_LiiklusService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffsetsReply.ProtoReflect.Descriptor instead.
func (*GetOffsetsReply) Descriptor() ([]byte, []int) {
	return file_LiiklusService_proto_rawDescGZIP(), []int{9}
}

func (x *GetOffsetsReply) GetOffsets() map[uint32]uint64 {
	if x != nil {
		return x.Offsets
	}
	return nil
}

type GetEndOffsetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndOffsetsRequest) Reset() {
	*x = GetEndOffsetsRequest{}
	mi := &file_LiiklusService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndOffsetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndOffsetsRequest) ProtoMessage() {}

func (x *GetEndOffsetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_LiiklusService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndOffsetsRequest.ProtoReflect.Descriptor instead.
func (*GetEndOffsetsRequest) Descriptor() ([]byte, []int) {
	return file_LiiklusService_proto_rawDescGZIP(), []int{10}
}

func (x *GetEndOffsetsRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type GetEndOffsetsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offsets       map[uint32]uint64      `protobuf:"bytes,1,rep,name=offsets,proto3" json:"offsets,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEndOffsetsReply) Reset() {
	*x = GetEndOffsetsReply{}
	mi := &file_LiiklusService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEndOffsetsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEndOffsetsReply) ProtoMessage() {}

func (x *GetEndOffsetsReply) ProtoReflect() protoreflect.Message {
	mi := &file_LiiklusService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEndOffsetsReply.ProtoReflect.Descriptor instead.
func (*GetEndOffsetsReply) Descriptor() ([]byte, []int) {
	return file_LiiklusService_proto_rawDescGZIP(), []int{11}
}

func (x *GetEndOffsetsReply) GetOffsets() map[uint32]uint64 {
	if x != nil {
		return x.Offsets
	}
	return nil
}

type ReceiveReply_Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Replay        bool                   `protobuf:"varint,5,opt,name=replay,proto3" json:"replay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiveReply_Record) Reset() {
	*x = ReceiveReply_Record{}
	mi := &file_LiiklusService_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiveReply_Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveReply_Record) ProtoMessage() {}

func (x *ReceiveReply_Record) ProtoReflect() protoreflect.Message {
	mi := &file_LiiklusService_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveReply_Record.ProtoReflect.Descriptor instead.
func (*ReceiveReply_Record) Descriptor() ([]byte, []int) {
	return file_LiiklusService_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ReceiveReply_Record) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReceiveReply_Record) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ReceiveReply_Record) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ReceiveReply_Record) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ReceiveReply_Record) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

var File_LiiklusService_proto protoreflect.FileDescriptor

const file_LiiklusService_proto_rawDesc = "" +
	"\n" +
	"\x14LiiklusService.proto\x12\x1acom.github.bsideup.liiklus\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"N\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\"Z\n" +
	"\fPublishReply\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\rR\tpartition\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\"\xf7\x01\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\"\n" +
	"\fgroupVersion\x18\x04 \x01(\rR\fgroupVersion\x12f\n" +
	"\x0fautoOffsetReset\x18\x03 \x01(\x0e2<.com.github.bsideup.liiklus.SubscribeRequest.AutoOffsetResetR\x0fautoOffsetReset\"+\n" +
	"\x0fAutoOffsetReset\x12\f\n" +
	"\bEARLIEST\x10\x00\x12\n" +
	"\n" +
	"\x06LATEST\x10\x01\"H\n" +
	"\n" +
	"Assignment\x12\x1c\n" +
	"\tsessionId\x18\x01 \x01(\tR\tsessionId\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\rR\tpartition\"c\n" +
	"\x0eSubscribeReply\x12H\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2&.com.github.bsideup.liiklus.AssignmentH\x00R\n" +
	"assignmentB\a\n" +
	"\x05reply\"\xde\x01\n" +
	"\n" +
	"AckRequest\x12J\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2&.com.github.bsideup.liiklus.AssignmentB\x02\x18\x01R\n" +
	"assignment\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\x12\"\n" +
	"\fgroupVersion\x18\x05 \x01(\rR\fgroupVersion\x12\x1c\n" +
	"\tpartition\x18\x06 \x01(\rR\tpartition\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\"\x82\x01\n" +
	"\x0eReceiveRequest\x12F\n" +
	"\n" +
	"assignment\x18\x01 \x01(\v2&.com.github.bsideup.liiklus.AssignmentR\n" +
	"assignment\x12(\n" +
	"\x0flastKnownOffset\x18\x02 \x01(\x04R\x0flastKnownOffset\"\xff\x01\n" +
	"\fReceiveReply\x12I\n" +
	"\x06record\x18\x01 \x01(\v2/.com.github.bsideup.liiklus.ReceiveReply.RecordH\x00R\x06record\x1a\x9a\x01\n" +
	"\x06Record\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06replay\x18\x05 \x01(\bR\x06replayB\a\n" +
	"\x05reply\"c\n" +
	"\x11GetOffsetsRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\"\n" +
	"\fgroupVersion\x18\x03 \x01(\rR\fgroupVersion\"\xa1\x01\n" +
	"\x0fGetOffsetsReply\x12R\n" +
	"\aoffsets\x18\x01 \x03(\v28.com.github.bsideup.liiklus.GetOffsetsReply.OffsetsEntryR\aoffsets\x1a:\n" +
	"\fOffsetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\",\n" +
	"\x14GetEndOffsetsRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"\xa7\x01\n" +
	"\x12GetEndOffsetsReply\x12U\n" +
	"\aoffsets\x18\x01 \x03(\v2;.com.github.bsideup.liiklus.GetEndOffsetsReply.OffsetsEntryR\aoffsets\x1a:\n" +
	"\fOffsetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x012\xed\x04\n" +
	"\x0eLiiklusService\x12a\n" +
	"\aPublish\x12*.com.github.bsideup.liiklus.PublishRequest\x1a(.com.github.bsideup.liiklus.PublishReply\"\x00\x12i\n" +
	"\tSubscribe\x12,.com.github.bsideup.liiklus.SubscribeRequest\x1a*.com.github.bsideup.liiklus.SubscribeReply\"\x000\x01\x12c\n" +
	"\aReceive\x12*.com.github.bsideup.liiklus.ReceiveRequest\x1a(.com.github.bsideup.liiklus.ReceiveReply\"\x000\x01\x12G\n" +
	"\x03Ack\x12&.com.github.bsideup.liiklus.AckRequest\x1a\x16.google.protobuf.Empty\"\x00\x12j\n" +
	"\n" +
	"GetOffsets\x12-.com.github.bsideup.liiklus.GetOffsetsRequest\x1a+.com.github.bsideup.liiklus.GetOffsetsReply\"\x00\x12s\n" +
	"\rGetEndOffsets\x120.com.github.bsideup.liiklus.GetEndOffsetsRequest\x1a..com.github.bsideup.liiklus.GetEndOffsetsReply\"\x00B5\n" +
	"#com.github.bsideup.liiklus.protocolH\x01P\x01Z\n" +
	"./;liiklusb\x06proto3"

var (
	file_LiiklusService_proto_rawDescOnce sync.Once
	file_LiiklusService_proto_rawDescData []byte
)

func file_LiiklusService_proto_rawDescGZIP() []byte {
	file_LiiklusService_proto_rawDescOnce.Do(func() {
		file_LiiklusService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_LiiklusService_proto_rawDesc), len(file_LiiklusService_proto_rawDesc)))
	})
	return file_LiiklusService_proto_rawDescData
}

var file_LiiklusService_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_LiiklusService_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_LiiklusService_proto_goTypes = []any{
	(SubscribeRequest_AutoOffsetReset)(0), // 0: com.github.bsideup.liiklus.SubscribeRequest.AutoOffsetReset
	(*PublishRequest)(nil),                // 1: com.github.bsideup.liiklus.PublishRequest
	(*PublishReply)(nil),                  // 2: com.github.bsideup.liiklus.PublishReply
	(*SubscribeRequest)(nil),              // 3: com.github.bsideup.liiklus.SubscribeRequest
	(*Assignment)(nil),                    // 4: com.github.bsideup.liiklus.Assignment
	(*SubscribeReply)(nil),                // 5: com.github.bsideup.liiklus.SubscribeReply
	(*AckRequest)(nil),                    // 6: com.github.bsideup.liiklus.AckRequest
	(*ReceiveRequest)(nil),                // 7: com.github.bsideup.liiklus.ReceiveRequest
	(*ReceiveReply)(nil),                  // 8: com.github.bsideup.liiklus.ReceiveReply
	(*GetOffsetsRequest)(nil),             // 9: com.github.bsideup.liiklus.GetOffsetsRequest
	(*GetOffsetsReply)(nil),               // 10: com.github.bsideup.liiklus.GetOffsetsReply
	(*GetEndOffsetsRequest)(nil),          // 11: com.github.bsideup.liiklus.GetEndOffsetsRequest
	(*GetEndOffsetsReply)(nil),            // 12: com.github.bsideup.liiklus.GetEndOffsetsReply
	(*ReceiveReply_Record)(nil),           // 13: com.github.bsideup.liiklus.ReceiveReply.Record
	nil,                                   // 14: com.github.bsideup.liiklus.GetOffsetsReply.OffsetsEntry
	nil,                                   // 15: com.github.bsideup.liiklus.GetEndOffsetsReply.OffsetsEntry
	(*timestamppb.Timestamp)(nil),         // 16: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 17: google.protobuf.Empty
}
var file_LiiklusService_proto_depIdxs = []int32{
	0,  // 0: com.github.bsideup.liiklus.SubscribeRequest.autoOffsetReset:type_name -> com.github.bsideup.liiklus.SubscribeRequest.AutoOffsetReset
	4,  // 1: com.github.bsideup.liiklus.SubscribeReply.assignment:type_name -> com.github.bsideup.liiklus.Assignment
	4,  // 2: com.github.bsideup.liiklus.AckRequest.assignment:type_name -> com.github.bsideup.liiklus.Assignment
	4,  // 3: com.github.bsideup.liiklus.ReceiveRequest.assignment:type_name -> com.github.bsideup.liiklus.Assignment
	13, // 4: com.github.bsideup.liiklus.ReceiveReply.record:type_name -> com.github.bsideup.liiklus.ReceiveReply.Record
	14, // 5: com.github.bsideup.liiklus.GetOffsetsReply.offsets:type_name -> com.github.bsideup.liiklus.GetOffsetsReply.OffsetsEntry
	15, // 6: com.github.bsideup.liiklus.GetEndOffsetsReply.offsets:type_name -> com.github.bsideup.liiklus.GetEndOffsetsReply.OffsetsEntry
	16, // 7: com.github.bsideup.liiklus.ReceiveReply.Record.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 8: com.github.bsideup.liiklus.LiiklusService.Publish:input_type -> com.github.bsideup.liiklus.PublishRequest
	3,  // 9: com.github.bsideup.liiklus.LiiklusService.Subscribe:input_type -> com.github.bsideup.liiklus.SubscribeRequest
	7,  // 10: com.github.bsideup.liiklus.LiiklusService.Receive:input_type -> com.github.bsideup.liiklus.ReceiveRequest
	6,  // 11: com.github.bsideup.liiklus.LiiklusService.Ack:input_type -> com.github.bsideup.liiklus.AckRequest
	9,  // 12: com.github.bsideup.liiklus.LiiklusService.GetOffsets:input_type -> com.github.bsideup.liiklus.GetOffsetsRequest
	11, // 13: com.github.bsideup.liiklus.LiiklusService.GetEndOffsets:input_type -> com.github.bsideup.liiklus.GetEndOffsetsRequest
	2,  // 14: com.github.bsideup.liiklus.LiiklusService.Publish:output_type -> com.github.bsideup.liiklus.PublishReply
	5,  // 15: com.github.bsideup.liiklus.LiiklusService.Subscribe:output_type -> com.github.bsideup.liiklus.SubscribeReply
	8,  // 16: com.github.bsideup.liiklus.LiiklusService.Receive:output_type -> com.github.bsideup.liiklus.ReceiveReply
	17, // 17: com.github.bsideup.liiklus.LiiklusService.Ack:output_type -> google.protobuf.Empty
	10, // 18: com.github.bsideup.liiklus.LiiklusService.GetOffsets:output_type -> com.github.bsideup.liiklus.GetOffsetsReply
	12, // 19: com.github.bsideup.liiklus.LiiklusService.GetEndOffsets:output_type -> com.github.bsideup.liiklus.GetEndOffsetsReply
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_LiiklusService_proto_init() }
func file_LiiklusService_proto_init() {
	if File_LiiklusService_proto != nil {
		return
	}
	file_LiiklusService_proto_msgTypes[4].OneofWrappers = []any{
		(*SubscribeReply_Assignment)(nil),
	}
	file_LiiklusService_proto_msgTypes[7].OneofWrappers = []any{
		(*ReceiveReply_Record_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_LiiklusService_proto_rawDesc), len(file_LiiklusService_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_LiiklusService_proto_goTypes,
		DependencyIndexes: file_LiiklusService_proto_depIdxs,
		EnumInfos:         file_LiiklusService_proto_enumTypes,
		MessageInfos:      file_LiiklusService_proto_msgTypes,
	}.Build()
	File_LiiklusService_proto = out.File
	file_LiiklusService_proto_goTypes = nil
	file_LiiklusService_proto_depIdxs = nil
}
