// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/scaling/executor/scale_executor.go
//
// Generated by this command:
//
//	mockgen -destination=pkg/mock/mock_scaling/mock_executor/mock_interface.go -package=mock_executor -source=pkg/scaling/executor/scale_executor.go
//

// Package mock_executor is a generated GoMock package.
package mock_executor

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	v1alpha1 "github.com/kedacore/keda/v2/apis/keda/v1alpha1"
	executor "github.com/kedacore/keda/v2/pkg/scaling/executor"
)

// MockScaleExecutor is a mock of ScaleExecutor interface.
type MockScaleExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockScaleExecutorMockRecorder
	isgomock struct{}
}

// MockScaleExecutorMockRecorder is the mock recorder for MockScaleExecutor.
type MockScaleExecutorMockRecorder struct {
	mock *MockScaleExecutor
}

// NewMockScaleExecutor creates a new mock instance.
func NewMockScaleExecutor(ctrl *gomock.Controller) *MockScaleExecutor {
	mock := &MockScaleExecutor{ctrl: ctrl}
	mock.recorder = &MockScaleExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScaleExecutor) EXPECT() *MockScaleExecutorMockRecorder {
	return m.recorder
}

// RequestJobScale mocks base method.
func (m *MockScaleExecutor) RequestJobScale(ctx context.Context, scaledJob *v1alpha1.ScaledJob, isActive, isError bool, scaleTo, maxScale int64, options *executor.ScaleExecutorOptions) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RequestJobScale", ctx, scaledJob, isActive, isError, scaleTo, maxScale, options)
}

// RequestJobScale indicates an expected call of RequestJobScale.
func (mr *MockScaleExecutorMockRecorder) RequestJobScale(ctx, scaledJob, isActive, isError, scaleTo, maxScale, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestJobScale", reflect.TypeOf((*MockScaleExecutor)(nil).RequestJobScale), ctx, scaledJob, isActive, isError, scaleTo, maxScale, options)
}

// RequestScale mocks base method.
func (m *MockScaleExecutor) RequestScale(ctx context.Context, scaledObject *v1alpha1.ScaledObject, isActive, isError bool, options *executor.ScaleExecutorOptions) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RequestScale", ctx, scaledObject, isActive, isError, options)
}

// RequestScale indicates an expected call of RequestScale.
func (mr *MockScaleExecutorMockRecorder) RequestScale(ctx, scaledObject, isActive, isError, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestScale", reflect.TypeOf((*MockScaleExecutor)(nil).RequestScale), ctx, scaledObject, isActive, isError, options)
}
