// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.6
// source: externalCalculation.proto

package externalCalculation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ExternalCalculationClient is the client API for ExternalCalculation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExternalCalculationClient interface {
	Calculate(ctx context.Context, in *MetricsList, opts ...grpc.CallOption) (*Response, error)
}

type externalCalculationClient struct {
	cc grpc.ClientConnInterface
}

func NewExternalCalculationClient(cc grpc.ClientConnInterface) ExternalCalculationClient {
	return &externalCalculationClient{cc}
}

func (c *externalCalculationClient) Calculate(ctx context.Context, in *MetricsList, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/externalCalculation.ExternalCalculation/Calculate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExternalCalculationServer is the server API for ExternalCalculation service.
// All implementations must embed UnimplementedExternalCalculationServer
// for forward compatibility
type ExternalCalculationServer interface {
	Calculate(context.Context, *MetricsList) (*Response, error)
	mustEmbedUnimplementedExternalCalculationServer()
}

// UnimplementedExternalCalculationServer must be embedded to have forward compatible implementations.
type UnimplementedExternalCalculationServer struct {
}

func (UnimplementedExternalCalculationServer) Calculate(context.Context, *MetricsList) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculate not implemented")
}
func (UnimplementedExternalCalculationServer) mustEmbedUnimplementedExternalCalculationServer() {}

// UnsafeExternalCalculationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExternalCalculationServer will
// result in compilation errors.
type UnsafeExternalCalculationServer interface {
	mustEmbedUnimplementedExternalCalculationServer()
}

func RegisterExternalCalculationServer(s grpc.ServiceRegistrar, srv ExternalCalculationServer) {
	s.RegisterService(&ExternalCalculation_ServiceDesc, srv)
}

func _ExternalCalculation_Calculate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricsList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExternalCalculationServer).Calculate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/externalCalculation.ExternalCalculation/Calculate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExternalCalculationServer).Calculate(ctx, req.(*MetricsList))
	}
	return interceptor(ctx, in, info, handler)
}

// ExternalCalculation_ServiceDesc is the grpc.ServiceDesc for ExternalCalculation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExternalCalculation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "externalCalculation.ExternalCalculation",
	HandlerType: (*ExternalCalculationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculate",
			Handler:    _ExternalCalculation_Calculate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "externalCalculation.proto",
}
