//go:build !ignore_autogenerated

/*
Copyright 2024 The KEDA Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	kedav1alpha1 "github.com/kedacore/keda/v2/apis/keda/v1alpha1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureEventGridTopicSpec) DeepCopyInto(out *AzureEventGridTopicSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureEventGridTopicSpec.
func (in *AzureEventGridTopicSpec) DeepCopy() *AzureEventGridTopicSpec {
	if in == nil {
		return nil
	}
	out := new(AzureEventGridTopicSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventHTTP) DeepCopyInto(out *CloudEventHTTP) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventHTTP.
func (in *CloudEventHTTP) DeepCopy() *CloudEventHTTP {
	if in == nil {
		return nil
	}
	out := new(CloudEventHTTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventSource) DeepCopyInto(out *CloudEventSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventSource.
func (in *CloudEventSource) DeepCopy() *CloudEventSource {
	if in == nil {
		return nil
	}
	out := new(CloudEventSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudEventSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventSourceList) DeepCopyInto(out *CloudEventSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudEventSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventSourceList.
func (in *CloudEventSourceList) DeepCopy() *CloudEventSourceList {
	if in == nil {
		return nil
	}
	out := new(CloudEventSourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudEventSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventSourceSpec) DeepCopyInto(out *CloudEventSourceSpec) {
	*out = *in
	in.Destination.DeepCopyInto(&out.Destination)
	in.EventSubscription.DeepCopyInto(&out.EventSubscription)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventSourceSpec.
func (in *CloudEventSourceSpec) DeepCopy() *CloudEventSourceSpec {
	if in == nil {
		return nil
	}
	out := new(CloudEventSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudEventSourceStatus) DeepCopyInto(out *CloudEventSourceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(kedav1alpha1.Conditions, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudEventSourceStatus.
func (in *CloudEventSourceStatus) DeepCopy() *CloudEventSourceStatus {
	if in == nil {
		return nil
	}
	out := new(CloudEventSourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Destination) DeepCopyInto(out *Destination) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(CloudEventHTTP)
		**out = **in
	}
	if in.AzureEventGridTopic != nil {
		in, out := &in.AzureEventGridTopic, &out.AzureEventGridTopic
		*out = new(AzureEventGridTopicSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Destination.
func (in *Destination) DeepCopy() *Destination {
	if in == nil {
		return nil
	}
	out := new(Destination)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventSubscription) DeepCopyInto(out *EventSubscription) {
	*out = *in
	if in.IncludedEventTypes != nil {
		in, out := &in.IncludedEventTypes, &out.IncludedEventTypes
		*out = make([]CloudEventType, len(*in))
		copy(*out, *in)
	}
	if in.ExcludedEventTypes != nil {
		in, out := &in.ExcludedEventTypes, &out.ExcludedEventTypes
		*out = make([]CloudEventType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventSubscription.
func (in *EventSubscription) DeepCopy() *EventSubscription {
	if in == nil {
		return nil
	}
	out := new(EventSubscription)
	in.DeepCopyInto(out)
	return out
}
