/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/Azure/Kore/pkg/apis/kore/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeScaledObjects implements ScaledObjectInterface
type FakeScaledObjects struct {
	Fake *FakeKoreV1alpha1
	ns   string
}

var scaledobjectsResource = schema.GroupVersionResource{Group: "kore.k8s.io", Version: "v1alpha1", Resource: "scaledobjects"}

var scaledobjectsKind = schema.GroupVersionKind{Group: "kore.k8s.io", Version: "v1alpha1", Kind: "ScaledObject"}

// Get takes name of the scaledObject, and returns the corresponding scaledObject object, and an error if there is any.
func (c *FakeScaledObjects) Get(name string, options v1.GetOptions) (result *v1alpha1.ScaledObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(scaledobjectsResource, c.ns, name), &v1alpha1.ScaledObject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScaledObject), err
}

// List takes label and field selectors, and returns the list of ScaledObjects that match those selectors.
func (c *FakeScaledObjects) List(opts v1.ListOptions) (result *v1alpha1.ScaledObjectList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(scaledobjectsResource, scaledobjectsKind, c.ns, opts), &v1alpha1.ScaledObjectList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ScaledObjectList{ListMeta: obj.(*v1alpha1.ScaledObjectList).ListMeta}
	for _, item := range obj.(*v1alpha1.ScaledObjectList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested scaledObjects.
func (c *FakeScaledObjects) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(scaledobjectsResource, c.ns, opts))

}

// Create takes the representation of a scaledObject and creates it.  Returns the server's representation of the scaledObject, and an error, if there is any.
func (c *FakeScaledObjects) Create(scaledObject *v1alpha1.ScaledObject) (result *v1alpha1.ScaledObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(scaledobjectsResource, c.ns, scaledObject), &v1alpha1.ScaledObject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScaledObject), err
}

// Update takes the representation of a scaledObject and updates it. Returns the server's representation of the scaledObject, and an error, if there is any.
func (c *FakeScaledObjects) Update(scaledObject *v1alpha1.ScaledObject) (result *v1alpha1.ScaledObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(scaledobjectsResource, c.ns, scaledObject), &v1alpha1.ScaledObject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScaledObject), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeScaledObjects) UpdateStatus(scaledObject *v1alpha1.ScaledObject) (*v1alpha1.ScaledObject, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(scaledobjectsResource, "status", c.ns, scaledObject), &v1alpha1.ScaledObject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScaledObject), err
}

// Delete takes name of the scaledObject and deletes it. Returns an error if one occurs.
func (c *FakeScaledObjects) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(scaledobjectsResource, c.ns, name), &v1alpha1.ScaledObject{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeScaledObjects) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(scaledobjectsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.ScaledObjectList{})
	return err
}

// Patch applies the patch and returns the patched scaledObject.
func (c *FakeScaledObjects) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ScaledObject, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(scaledobjectsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ScaledObject{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScaledObject), err
}
