name: Reusable workflow to run trivy scan

on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      scan-type:
        required: true
        type: string
      format:
        required: true
        type: string
      output:
        required: false
        type: string
        default: trivy.sarif
      image-ref:
        required: false
        type: string
        default: ""
      severity:
        required: false
        type: string
        default: "CRITICAL,HIGH"
      exit-code:
        required: true
        type: number
      publish:
        required: true
        type: boolean

permissions:
  contents: read

jobs:
  trivy-scan:
    name: Trivy - ${{ inputs.runs-on }} - ${{ inputs.scan-type }} ${{ inputs.image-ref }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run Trivy
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.34.2
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/kedacore/trivy-db
        with:
          scan-type: ${{ inputs.scan-type }}
          image-ref: ${{ inputs.image-ref }}
          ignore-unfixed: false
          format: ${{ inputs.format }}
          output: ${{ inputs.output }}
          exit-code: ${{ inputs.exit-code }}
          severity: ${{ inputs.severity }}
          trivy-config: trivy.yml

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13 # v4.35.1
        if: ${{ inputs.publish }}
        with:
          sarif_file: ${{ inputs.output }}
