name: Reusable workflow to run smoke tests on s390x

on:
  workflow_call:

jobs:
  smoke-tests-s390x:
    name: s390x
    concurrency: s390x-smoke-tests
    uses: kedacore/keda/.github/workflows/template-smoke-tests.yml@main
    with:
      runs-on: s390x
      kubernetesVersion: v1.32
      kindImage: kindest/node:v1.32.0@sha256:c48c62eac5da28cdadcf560d1d8616cfa6783b58f0d94cf63ad1bf49600cb027
