//
//Copyright 2022 The KEDA Authors
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.35.0
// source: metrics.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScaledObjectRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	MetricName    string                 `protobuf:"bytes,3,opt,name=metricName,proto3" json:"metricName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaledObjectRef) Reset() {
	*x = ScaledObjectRef{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaledObjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaledObjectRef) ProtoMessage() {}

func (x *ScaledObjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaledObjectRef.ProtoReflect.Descriptor instead.
func (*ScaledObjectRef) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *ScaledObjectRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScaledObjectRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ScaledObjectRef) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

type RawMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriber    string                 `protobuf:"bytes,1,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawMetricsRequest) Reset() {
	*x = RawMetricsRequest{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawMetricsRequest) ProtoMessage() {}

func (x *RawMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawMetricsRequest.ProtoReflect.Descriptor instead.
func (*RawMetricsRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *RawMetricsRequest) GetSubscriber() string {
	if x != nil {
		return x.Subscriber
	}
	return ""
}

type SubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Subscriber     string                 `protobuf:"bytes,1,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
	MetricMetadata *ScaledObjectRef       `protobuf:"bytes,2,opt,name=metricMetadata,proto3" json:"metricMetadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *SubscriptionRequest) GetSubscriber() string {
	if x != nil {
		return x.Subscriber
	}
	return ""
}

func (x *SubscriptionRequest) GetMetricMetadata() *ScaledObjectRef {
	if x != nil {
		return x.MetricMetadata
	}
	return nil
}

type SubscriptionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WasSubscribed bool                   `protobuf:"varint,1,opt,name=wasSubscribed,proto3" json:"wasSubscribed,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionAck) Reset() {
	*x = SubscriptionAck{}
	mi := &file_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionAck) ProtoMessage() {}

func (x *SubscriptionAck) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionAck.ProtoReflect.Descriptor instead.
func (*SubscriptionAck) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *SubscriptionAck) GetWasSubscribed() bool {
	if x != nil {
		return x.WasSubscribed
	}
	return false
}

func (x *SubscriptionAck) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type RawMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*RawMetric           `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawMetricsResponse) Reset() {
	*x = RawMetricsResponse{}
	mi := &file_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawMetricsResponse) ProtoMessage() {}

func (x *RawMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawMetricsResponse.ProtoReflect.Descriptor instead.
func (*RawMetricsResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *RawMetricsResponse) GetMetrics() []*RawMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type RawMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      *ScaledObjectRef       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=isActive,proto3" json:"isActive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawMetric) Reset() {
	*x = RawMetric{}
	mi := &file_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawMetric) ProtoMessage() {}

func (x *RawMetric) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawMetric.ProtoReflect.Descriptor instead.
func (*RawMetric) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *RawMetric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *RawMetric) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RawMetric) GetMetadata() *ScaledObjectRef {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RawMetric) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// These messages mirror the wire shape of
// k8s.io.metrics.pkg.apis.external_metrics.v1beta1.ExternalMetricValueList
// without importing Kubernetes API structs as gRPC response types.
type ExternalMetricValueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ListMeta              `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Items         []*ExternalMetricValue `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalMetricValueList) Reset() {
	*x = ExternalMetricValueList{}
	mi := &file_metrics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalMetricValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalMetricValueList) ProtoMessage() {}

func (x *ExternalMetricValueList) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalMetricValueList.ProtoReflect.Descriptor instead.
func (*ExternalMetricValueList) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{6}
}

func (x *ExternalMetricValueList) GetMetadata() *ListMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExternalMetricValueList) GetItems() []*ExternalMetricValue {
	if x != nil {
		return x.Items
	}
	return nil
}

type ExternalMetricValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricName    string                 `protobuf:"bytes,1,opt,name=metricName,proto3" json:"metricName,omitempty"`
	MetricLabels  map[string]string      `protobuf:"bytes,2,rep,name=metricLabels,proto3" json:"metricLabels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *Time                  `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Window        *int64                 `protobuf:"varint,4,opt,name=window,proto3,oneof" json:"window,omitempty"`
	Value         *Quantity              `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalMetricValue) Reset() {
	*x = ExternalMetricValue{}
	mi := &file_metrics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalMetricValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalMetricValue) ProtoMessage() {}

func (x *ExternalMetricValue) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalMetricValue.ProtoReflect.Descriptor instead.
func (*ExternalMetricValue) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{7}
}

func (x *ExternalMetricValue) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *ExternalMetricValue) GetMetricLabels() map[string]string {
	if x != nil {
		return x.MetricLabels
	}
	return nil
}

func (x *ExternalMetricValue) GetTimestamp() *Time {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ExternalMetricValue) GetWindow() int64 {
	if x != nil && x.Window != nil {
		return *x.Window
	}
	return 0
}

func (x *ExternalMetricValue) GetValue() *Quantity {
	if x != nil {
		return x.Value
	}
	return nil
}

type ListMeta struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SelfLink           string                 `protobuf:"bytes,1,opt,name=selfLink,proto3" json:"selfLink,omitempty"`
	ResourceVersion    string                 `protobuf:"bytes,2,opt,name=resourceVersion,proto3" json:"resourceVersion,omitempty"`
	Continue           string                 `protobuf:"bytes,3,opt,name=continue,proto3" json:"continue,omitempty"`
	RemainingItemCount *int64                 `protobuf:"varint,4,opt,name=remainingItemCount,proto3,oneof" json:"remainingItemCount,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListMeta) Reset() {
	*x = ListMeta{}
	mi := &file_metrics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMeta) ProtoMessage() {}

func (x *ListMeta) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMeta.ProtoReflect.Descriptor instead.
func (*ListMeta) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{8}
}

func (x *ListMeta) GetSelfLink() string {
	if x != nil {
		return x.SelfLink
	}
	return ""
}

func (x *ListMeta) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *ListMeta) GetContinue() string {
	if x != nil {
		return x.Continue
	}
	return ""
}

func (x *ListMeta) GetRemainingItemCount() int64 {
	if x != nil && x.RemainingItemCount != nil {
		return *x.RemainingItemCount
	}
	return 0
}

// Time mirrors k8s.io/apimachinery/pkg/apis/meta/v1.Time on the wire.
type Time struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       int64                  `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
	Nanos         int32                  `protobuf:"varint,2,opt,name=nanos,proto3" json:"nanos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Time) Reset() {
	*x = Time{}
	mi := &file_metrics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Time) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Time) ProtoMessage() {}

func (x *Time) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Time.ProtoReflect.Descriptor instead.
func (*Time) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{9}
}

func (x *Time) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *Time) GetNanos() int32 {
	if x != nil {
		return x.Nanos
	}
	return 0
}

// Quantity mirrors k8s.io/apimachinery/pkg/api/resource.Quantity on the wire.
type Quantity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	String_       string                 `protobuf:"bytes,1,opt,name=string,proto3" json:"string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quantity) Reset() {
	*x = Quantity{}
	mi := &file_metrics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quantity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quantity) ProtoMessage() {}

func (x *Quantity) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quantity.ProtoReflect.Descriptor instead.
func (*Quantity) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{10}
}

func (x *Quantity) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\"c\n" +
	"\x0fScaledObjectRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"metricName\x18\x03 \x01(\tR\n" +
	"metricName\"3\n" +
	"\x11RawMetricsRequest\x12\x1e\n" +
	"\n" +
	"subscriber\x18\x01 \x01(\tR\n" +
	"subscriber\"s\n" +
	"\x13SubscriptionRequest\x12\x1e\n" +
	"\n" +
	"subscriber\x18\x01 \x01(\tR\n" +
	"subscriber\x12<\n" +
	"\x0emetricMetadata\x18\x02 \x01(\v2\x14.api.ScaledObjectRefR\x0emetricMetadata\"b\n" +
	"\x0fSubscriptionAck\x12$\n" +
	"\rwasSubscribed\x18\x01 \x01(\bR\rwasSubscribed\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\">\n" +
	"\x12RawMetricsResponse\x12(\n" +
	"\ametrics\x18\x01 \x03(\v2\x0e.api.RawMetricR\ametrics\"\xa9\x01\n" +
	"\tRawMetric\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x120\n" +
	"\bmetadata\x18\x03 \x01(\v2\x14.api.ScaledObjectRefR\bmetadata\x12\x1a\n" +
	"\bisActive\x18\x04 \x01(\bR\bisActive\"t\n" +
	"\x17ExternalMetricValueList\x12)\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.api.ListMetaR\bmetadata\x12.\n" +
	"\x05items\x18\x02 \x03(\v2\x18.api.ExternalMetricValueR\x05items\"\xbc\x02\n" +
	"\x13ExternalMetricValue\x12\x1e\n" +
	"\n" +
	"metricName\x18\x01 \x01(\tR\n" +
	"metricName\x12N\n" +
	"\fmetricLabels\x18\x02 \x03(\v2*.api.ExternalMetricValue.MetricLabelsEntryR\fmetricLabels\x12'\n" +
	"\ttimestamp\x18\x03 \x01(\v2\t.api.TimeR\ttimestamp\x12\x1b\n" +
	"\x06window\x18\x04 \x01(\x03H\x00R\x06window\x88\x01\x01\x12#\n" +
	"\x05value\x18\x05 \x01(\v2\r.api.QuantityR\x05value\x1a?\n" +
	"\x11MetricLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\a_window\"\xb8\x01\n" +
	"\bListMeta\x12\x1a\n" +
	"\bselfLink\x18\x01 \x01(\tR\bselfLink\x12(\n" +
	"\x0fresourceVersion\x18\x02 \x01(\tR\x0fresourceVersion\x12\x1a\n" +
	"\bcontinue\x18\x03 \x01(\tR\bcontinue\x123\n" +
	"\x12remainingItemCount\x18\x04 \x01(\x03H\x00R\x12remainingItemCount\x88\x01\x01B\x15\n" +
	"\x13_remainingItemCount\"6\n" +
	"\x04Time\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\x03R\aseconds\x12\x14\n" +
	"\x05nanos\x18\x02 \x01(\x05R\x05nanos\"\"\n" +
	"\bQuantity\x12\x16\n" +
	"\x06string\x18\x01 \x01(\tR\x06string2T\n" +
	"\x0eMetricsService\x12B\n" +
	"\n" +
	"GetMetrics\x12\x14.api.ScaledObjectRef\x1a\x1c.api.ExternalMetricValueList\"\x002\xeb\x01\n" +
	"\x11RawMetricsService\x12J\n" +
	"\x13GetRawMetricsStream\x12\x16.api.RawMetricsRequest\x1a\x17.api.RawMetricsResponse\"\x000\x01\x12C\n" +
	"\x0fSubscribeMetric\x12\x18.api.SubscriptionRequest\x1a\x14.api.SubscriptionAck\"\x00\x12E\n" +
	"\x11UnsubscribeMetric\x12\x18.api.SubscriptionRequest\x1a\x14.api.SubscriptionAck\"\x00B\aZ\x05.;apib\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_metrics_proto_goTypes = []any{
	(*ScaledObjectRef)(nil),         // 0: api.ScaledObjectRef
	(*RawMetricsRequest)(nil),       // 1: api.RawMetricsRequest
	(*SubscriptionRequest)(nil),     // 2: api.SubscriptionRequest
	(*SubscriptionAck)(nil),         // 3: api.SubscriptionAck
	(*RawMetricsResponse)(nil),      // 4: api.RawMetricsResponse
	(*RawMetric)(nil),               // 5: api.RawMetric
	(*ExternalMetricValueList)(nil), // 6: api.ExternalMetricValueList
	(*ExternalMetricValue)(nil),     // 7: api.ExternalMetricValue
	(*ListMeta)(nil),                // 8: api.ListMeta
	(*Time)(nil),                    // 9: api.Time
	(*Quantity)(nil),                // 10: api.Quantity
	nil,                             // 11: api.ExternalMetricValue.MetricLabelsEntry
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
}
var file_metrics_proto_depIdxs = []int32{
	0,  // 0: api.SubscriptionRequest.metricMetadata:type_name -> api.ScaledObjectRef
	5,  // 1: api.RawMetricsResponse.metrics:type_name -> api.RawMetric
	12, // 2: api.RawMetric.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 3: api.RawMetric.metadata:type_name -> api.ScaledObjectRef
	8,  // 4: api.ExternalMetricValueList.metadata:type_name -> api.ListMeta
	7,  // 5: api.ExternalMetricValueList.items:type_name -> api.ExternalMetricValue
	11, // 6: api.ExternalMetricValue.metricLabels:type_name -> api.ExternalMetricValue.MetricLabelsEntry
	9,  // 7: api.ExternalMetricValue.timestamp:type_name -> api.Time
	10, // 8: api.ExternalMetricValue.value:type_name -> api.Quantity
	0,  // 9: api.MetricsService.GetMetrics:input_type -> api.ScaledObjectRef
	1,  // 10: api.RawMetricsService.GetRawMetricsStream:input_type -> api.RawMetricsRequest
	2,  // 11: api.RawMetricsService.SubscribeMetric:input_type -> api.SubscriptionRequest
	2,  // 12: api.RawMetricsService.UnsubscribeMetric:input_type -> api.SubscriptionRequest
	6,  // 13: api.MetricsService.GetMetrics:output_type -> api.ExternalMetricValueList
	4,  // 14: api.RawMetricsService.GetRawMetricsStream:output_type -> api.RawMetricsResponse
	3,  // 15: api.RawMetricsService.SubscribeMetric:output_type -> api.SubscriptionAck
	3,  // 16: api.RawMetricsService.UnsubscribeMetric:output_type -> api.SubscriptionAck
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	file_metrics_proto_msgTypes[3].OneofWrappers = []any{}
	file_metrics_proto_msgTypes[7].OneofWrappers = []any{}
	file_metrics_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
