//
//Copyright 2022 The KEDA Authors
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: metrics.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	v1beta1 "k8s.io/metrics/pkg/apis/external_metrics/v1beta1"
	"reflect"
	"sync"
	"unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScaledObjectRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	MetricName    string                 `protobuf:"bytes,3,opt,name=metricName,proto3" json:"metricName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScaledObjectRef) Reset() {
	*x = ScaledObjectRef{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScaledObjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScaledObjectRef) ProtoMessage() {}

func (x *ScaledObjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScaledObjectRef.ProtoReflect.Descriptor instead.
func (*ScaledObjectRef) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *ScaledObjectRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScaledObjectRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ScaledObjectRef) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

type RawMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriber    string                 `protobuf:"bytes,1,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawMetricsRequest) Reset() {
	*x = RawMetricsRequest{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawMetricsRequest) ProtoMessage() {}

func (x *RawMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawMetricsRequest.ProtoReflect.Descriptor instead.
func (*RawMetricsRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *RawMetricsRequest) GetSubscriber() string {
	if x != nil {
		return x.Subscriber
	}
	return ""
}

type SubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Subscriber     string                 `protobuf:"bytes,1,opt,name=subscriber,proto3" json:"subscriber,omitempty"`
	MetricMetadata *ScaledObjectRef       `protobuf:"bytes,2,opt,name=metricMetadata,proto3" json:"metricMetadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscriptionRequest) Reset() {
	*x = SubscriptionRequest{}
	mi := &file_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionRequest) ProtoMessage() {}

func (x *SubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *SubscriptionRequest) GetSubscriber() string {
	if x != nil {
		return x.Subscriber
	}
	return ""
}

func (x *SubscriptionRequest) GetMetricMetadata() *ScaledObjectRef {
	if x != nil {
		return x.MetricMetadata
	}
	return nil
}

type SubscriptionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WasSubscribed bool                   `protobuf:"varint,1,opt,name=wasSubscribed,proto3" json:"wasSubscribed,omitempty"`
	Message       *string                `protobuf:"bytes,2,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionAck) Reset() {
	*x = SubscriptionAck{}
	mi := &file_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionAck) ProtoMessage() {}

func (x *SubscriptionAck) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionAck.ProtoReflect.Descriptor instead.
func (*SubscriptionAck) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *SubscriptionAck) GetWasSubscribed() bool {
	if x != nil {
		return x.WasSubscribed
	}
	return false
}

func (x *SubscriptionAck) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type RawMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*RawMetric           `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawMetricsResponse) Reset() {
	*x = RawMetricsResponse{}
	mi := &file_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawMetricsResponse) ProtoMessage() {}

func (x *RawMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawMetricsResponse.ProtoReflect.Descriptor instead.
func (*RawMetricsResponse) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *RawMetricsResponse) GetMetrics() []*RawMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type RawMetric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      *ScaledObjectRef       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=isActive,proto3" json:"isActive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawMetric) Reset() {
	*x = RawMetric{}
	mi := &file_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawMetric) ProtoMessage() {}

func (x *RawMetric) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawMetric.ProtoReflect.Descriptor instead.
func (*RawMetric) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *RawMetric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *RawMetric) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *RawMetric) GetMetadata() *ScaledObjectRef {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RawMetric) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a@k8s.io/metrics/pkg/apis/external_metrics/v1beta1/generated.proto\"c\n" +
	"\x0fScaledObjectRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1e\n" +
	"\n" +
	"metricName\x18\x03 \x01(\tR\n" +
	"metricName\"3\n" +
	"\x11RawMetricsRequest\x12\x1e\n" +
	"\n" +
	"subscriber\x18\x01 \x01(\tR\n" +
	"subscriber\"s\n" +
	"\x13SubscriptionRequest\x12\x1e\n" +
	"\n" +
	"subscriber\x18\x01 \x01(\tR\n" +
	"subscriber\x12<\n" +
	"\x0emetricMetadata\x18\x02 \x01(\v2\x14.api.ScaledObjectRefR\x0emetricMetadata\"b\n" +
	"\x0fSubscriptionAck\x12$\n" +
	"\rwasSubscribed\x18\x01 \x01(\bR\rwasSubscribed\x12\x1d\n" +
	"\amessage\x18\x02 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\">\n" +
	"\x12RawMetricsResponse\x12(\n" +
	"\ametrics\x18\x01 \x03(\v2\x0e.api.RawMetricR\ametrics\"\xa9\x01\n" +
	"\tRawMetric\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x120\n" +
	"\bmetadata\x18\x03 \x01(\v2\x14.api.ScaledObjectRefR\bmetadata\x12\x1a\n" +
	"\bisActive\x18\x04 \x01(\bR\bisActive2\x81\x01\n" +
	"\x0eMetricsService\x12o\n" +
	"\n" +
	"GetMetrics\x12\x14.api.ScaledObjectRef\x1aI.k8s.io.metrics.pkg.apis.external_metrics.v1beta1.ExternalMetricValueList\"\x002\xeb\x01\n" +
	"\x11RawMetricsService\x12J\n" +
	"\x13GetRawMetricsStream\x12\x16.api.RawMetricsRequest\x1a\x17.api.RawMetricsResponse\"\x000\x01\x12C\n" +
	"\x0fSubscribeMetric\x12\x18.api.SubscriptionRequest\x1a\x14.api.SubscriptionAck\"\x00\x12E\n" +
	"\x11UnsubscribeMetric\x12\x18.api.SubscriptionRequest\x1a\x14.api.SubscriptionAck\"\x00B\aZ\x05.;apib\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_metrics_proto_goTypes = []any{
	(*ScaledObjectRef)(nil),                 // 0: api.ScaledObjectRef
	(*RawMetricsRequest)(nil),               // 1: api.RawMetricsRequest
	(*SubscriptionRequest)(nil),             // 2: api.SubscriptionRequest
	(*SubscriptionAck)(nil),                 // 3: api.SubscriptionAck
	(*RawMetricsResponse)(nil),              // 4: api.RawMetricsResponse
	(*RawMetric)(nil),                       // 5: api.RawMetric
	(*timestamppb.Timestamp)(nil),           // 6: google.protobuf.Timestamp
	(*v1beta1.ExternalMetricValueList)(nil), // 7: k8s.io.metrics.pkg.apis.external_metrics.v1beta1.ExternalMetricValueList
}
var file_metrics_proto_depIdxs = []int32{
	0, // 0: api.SubscriptionRequest.metricMetadata:type_name -> api.ScaledObjectRef
	5, // 1: api.RawMetricsResponse.metrics:type_name -> api.RawMetric
	6, // 2: api.RawMetric.timestamp:type_name -> google.protobuf.Timestamp
	0, // 3: api.RawMetric.metadata:type_name -> api.ScaledObjectRef
	0, // 4: api.MetricsService.GetMetrics:input_type -> api.ScaledObjectRef
	1, // 5: api.RawMetricsService.GetRawMetricsStream:input_type -> api.RawMetricsRequest
	2, // 6: api.RawMetricsService.SubscribeMetric:input_type -> api.SubscriptionRequest
	2, // 7: api.RawMetricsService.UnsubscribeMetric:input_type -> api.SubscriptionRequest
	7, // 8: api.MetricsService.GetMetrics:output_type -> k8s.io.metrics.pkg.apis.external_metrics.v1beta1.ExternalMetricValueList
	4, // 9: api.RawMetricsService.GetRawMetricsStream:output_type -> api.RawMetricsResponse
	3, // 10: api.RawMetricsService.SubscribeMetric:output_type -> api.SubscriptionAck
	3, // 11: api.RawMetricsService.UnsubscribeMetric:output_type -> api.SubscriptionAck
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	file_metrics_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
