//go:build e2e
// +build e2e

package forgejo_runner_test

import (
	"fmt"
	"os"
	"testing"
	"time"

	"github.com/joho/godotenv"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"k8s.io/client-go/kubernetes"

	. "github.com/kedacore/keda/v2/tests/helper" // For helper methods
)

// Load environment variables from .env file
var _ = godotenv.Load("../../.env")

const (
	testName = "forgejo-test"
)

var (
	testNamespace    = fmt.Sprintf("%s-ns", testName)
	deploymentName   = fmt.Sprintf("%s-deployment", testName)
	scaledJobName    = fmt.Sprintf("%s-so", testName)
	configName       = fmt.Sprintf("%s-configmap", testName)
	registrationName = fmt.Sprintf("%s-registration", testName)
	newTimestamp     = time.Now().Unix()

	forgejoRunnerName  = "forgejo-runner"
	forgejoToken       = os.Getenv("FORGEJO_TOKEN")
	forgejoGlobal      = "true"
	forgejoLabel       = "ubuntu-20.04"
	forgejoAccessToken = os.Getenv("FORGEJO_ACCESS_TOKEN")
	forgejoAddress     = fmt.Sprintf("http://forgejo-service.%s.svc.cluster.local:3000", testNamespace)

	minReplicaCount = 1
	maxReplicaCount = 2
)

type templateData struct {
	TestNamespace    string
	DeploymentName   string
	ScaledObjectName string
	ConfigName       string
	RegistrationName string
	NewTimestamp     int64

	ForgejoRunnerName  string
	ForgejoToken       string
	ForgejoGlobal      string
	ForgejoLabel       string
	ForgejoAccessToken string
	ForgejoAddress     string
}

const (
	forgejoService = `
apiVersion: v1
kind: Service
metadata:
  labels:
    app: forgejo
  name: forgejo-service
  namespace: {{.TestNamespace}}
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: forgejo
  type: ClusterIP
`

	forgejoDeployment = `
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: forgejo
  name: forgejo
  namespace: {{.TestNamespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      containers:
      - image: ghcr.io/kedacore/tests-forgejo:latest
        command:
          - sh
          - -c
          - |
            sqlite3 /data/forgejo.db "UPDATE action_run_job SET created = {{.NewTimestamp}} WHERE id = 3"
            sqlite3 /data/forgejo.db "UPDATE action_run_job SET updated = {{.NewTimestamp}} WHERE id = 3"
            sleep 5
            /usr/local/bin/gitea --config /data/app.ini web
        imagePullPolicy: IfNotPresent
        name: forgejo
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
 `
	runnerRegistration = `apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.RegistrationName}}
  namespace: {{.TestNamespace}}
data:
  registration.yaml: |
    runner:
      file: /data/.runner
      capacity: 1
      envs:
        DOCKER_HOST: tcp://localhost:2376
        DOCKER_TLS_VERIFY: 1
        DOCKER_CERT_PATH: /certs/client
      labels: 
        - ubuntu-20.04:docker://node:20-bookworm

    container:
      network: host
      options: -v /certs/client:/certs/client
      valid_volumes:
        - /certs/client
`

	runnerConfigMap = `apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.ConfigName}}
  namespace: {{.TestNamespace}}
data:
  runner.json: |
    {
      "WARNING": "This file is automatically generated by act-runner. Do not edit it manually unless you know what you are doing. Removing this file will cause act runner to re-register as a new runner.",
      "id": 2,
      "uuid": "bbbed033-ea94-4b44-a3c1-b4e347589a15",
      "name": "5c61760e58c5",
      "token": "{{.ForgejoToken}}",
      "address": "{{.ForgejoAddress}}",
      "labels": [
        "ubuntu-20.04:docker://node:20-bookworm"
      ]
    }
`

	scaledJob = `apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  labels:
    app: forgejo-runner
  name: forgejo-runner
  namespace: {{.TestNamespace}}
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: forgejo-job
      spec:
        volumes:
        - name: runner-data
          emptyDir: {}
        - name: runner-config
          configMap:
            name: {{.ConfigName}}
        - name: runner-registration
          configMap:
            name: {{.RegistrationName}}
        - name: docker-certs
          emptyDir: {}
        restartPolicy: Never
        shareProcessNamespace: true
        containers:
        - name: runner
          image: code.forgejo.org/forgejo/runner:6.3.1
          command: 
            - sh
            - -c
            - | 
              while ! nc -z localhost 2376 </dev/null; do 
                echo 'waiting for docker daemon...'
                sleep 5
              done

              cp /config/runner.json /data/.runner

              exec forgejo-runner -c /registration/registration.yaml one-job
          securityContext:
            privileged: true
            runAsUser: 0
          env:
          - name: DOCKER_HOST
            value: tcp://localhost:2376
          - name: DOCKER_CERT_PATH
            value: /certs/client
          - name: DOCKER_TLS_VERIFY
            value: "1"
          volumeMounts:
          - name: docker-certs
            mountPath: /certs
          - name: runner-data
            mountPath: /data
          - name: runner-registration
            mountPath: /registration
            readOnly: false
          - name: runner-config
            mountPath: /config
            readOnly: false
        - name: daemon
          image: docker:27.4.1-dind
          command: 
            - sh
            - -c
            - |
              dockerd-entrypoint.sh 2>&1 &

              while kill -0 7 2>/dev/null
                do sleep 10 
                echo "watching main job execution"
              done;

              sleep 10

              echo "main continaer exited, stopping dind"
              exit 0
          env:
          - name: DOCKER_TLS_CERTDIR
            value: /certs
          - name: DOCKER_HOST
            value: tcp://0.0.0.0:2376
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
          - name: docker-certs
            mountPath: /certs
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 5
  triggers:
  - type: forgejo-runner
    metadata:
      name: "{{.ForgejoRunnerName}}"
      token: "{{.ForgejoAccessToken}}"
      address: "{{.ForgejoAddress}}"
      global: "{{.ForgejoGlobal}}"
      labels: "{{.ForgejoLabel}}"
`
)

func TestForgejoScaler(t *testing.T) {
	// setting up
	t.Log("--- setting up ---")
	require.NotEmpty(t, forgejoToken, "FORGEJO_TOKEN env variable is required")
	require.NotEmpty(t, forgejoAccessToken, "FORGEJO_ACCESS_TOKEN env variable is required")

	kc := GetKubernetesClient(t)
	data_forgejo, templates_forgejo := getForgejoData()
	t.Cleanup(func() {

	})

	CreateNamespace(t, kc, testNamespace)
	KubectlApplyMultipleWithTemplate(t, data_forgejo, templates_forgejo)

	// setup forgejo
	setupForgejo(t, kc)

	data, templates := getTemplateData()
	t.Cleanup(func() {
		DeleteKubernetesResources(t, testNamespace, data_forgejo, append(templates, templates_forgejo...))
	})

	// Create kubernetes resources
	KubectlApplyMultipleWithTemplate(t, data, templates)

	// test scaling
	testScaleOut(t, kc)
	testScaleIn(t, kc)
}
func getForgejoData() (templateData, []Template) {
	return templateData{
			TestNamespace:      testNamespace,
			DeploymentName:     deploymentName,
			NewTimestamp:       newTimestamp,
			ScaledObjectName:   scaledJobName,
			ConfigName:         configName,
			RegistrationName:   registrationName,
			ForgejoRunnerName:  forgejoRunnerName,
			ForgejoToken:       forgejoToken,
			ForgejoGlobal:      forgejoGlobal,
			ForgejoLabel:       forgejoLabel,
			ForgejoAccessToken: forgejoAccessToken,
			ForgejoAddress:     forgejoAddress,
		}, []Template{
			{Name: "forgejoDeploymentTemplate", Config: forgejoDeployment},
			{Name: "forgejoServiceTemplate", Config: forgejoService},
			{Name: "registrationConfigMapTemplate", Config: runnerRegistration},
			{Name: "runnerConfigMapTemplate", Config: runnerConfigMap},
		}
}
func getTemplateData() (templateData, []Template) {
	return templateData{
			TestNamespace:      testNamespace,
			DeploymentName:     deploymentName,
			NewTimestamp:       newTimestamp,
			ScaledObjectName:   scaledJobName,
			ConfigName:         configName,
			RegistrationName:   registrationName,
			ForgejoRunnerName:  forgejoRunnerName,
			ForgejoToken:       forgejoToken,
			ForgejoGlobal:      forgejoGlobal,
			ForgejoLabel:       forgejoLabel,
			ForgejoAccessToken: forgejoAccessToken,
			ForgejoAddress:     forgejoAddress,
		}, []Template{
			{Name: "scaledObjectTemplate", Config: scaledJob},
		}
}

func setupForgejo(t *testing.T, kc *kubernetes.Clientset) {
	require.True(t,
		WaitForDeploymentReplicaReadyCount(t, kc, "forgejo", testNamespace, 1, 3, 20),
		"Forgejo should be running after 1 minute")
}

// pre-loaded database should scale automatically on defined label ubuntu-20.04
func testScaleOut(t *testing.T, kc *kubernetes.Clientset) {
	t.Log("--- testing scale out ---")

	assert.True(t, WaitForPodCountInNamespace(t, kc, testNamespace, maxReplicaCount, 60, 5), "pods count should be 2 after 1 minute")
}

func testScaleIn(t *testing.T, kc *kubernetes.Clientset) {
	t.Log("--- testing scale in ---")

	assert.True(t, WaitForPodCountInNamespace(t, kc, testNamespace, minReplicaCount, 60, 1), "pods count should be 1 after 1 minute")
}
