//go:build e2e
// +build e2e

package forgejo_runner_test

import (
	"fmt"
	"os"
	"testing"

	"github.com/joho/godotenv"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"k8s.io/client-go/kubernetes"

	. "github.com/kedacore/keda/v2/tests/helper" // For helper methods
)

// Load environment variables from .env file
var _ = godotenv.Load("../../.env")

const (
	testName = "forgejo-test"
)

var (
	testNamespace  = fmt.Sprintf("%s-ns", testName)
	deploymentName = fmt.Sprintf("%s-deployment", testName)
	scaledJobName  = fmt.Sprintf("%s-so", testName)
	configName     = fmt.Sprintf("%s-configmap", testName)

	forgejoRunnerName  = "forgejo-runner"
	forgejoToken       = os.Getenv("FORGEJO_TOKEN")
	forgejoGlobal      = "true"
	forgejoLabel       = "ubuntu-20.04"
	forgejoAccessToken = os.Getenv("FORGEJO_ACCESS_TOKEN")
	forgejoAddress     = os.Getenv("FORGEJO_ADDRESS")

	minReplicaCount = 1
	maxReplicaCount = 2
)

type templateData struct {
	TestNamespace    string
	DeploymentName   string
	ScaledObjectName string
	ConfigName       string

	ForgejoRunnerName  string
	ForgejoToken       string
	ForgejoGlobal      string
	ForgejoLabel       string
	ForgejoAccessToken string
	ForgejoAddress     string
}

const (
	forgejoService = `
apiVersion: v1
kind: Service
metadata:
  labels:
    app: forgejo
  name: forgejo-service
  namespace: {{.TestNamespace}}
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: forgejo
  type: ClusterIP
`

	forgejoDeployment = `
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: forgejo
  name: forgejo
  namespace: {{.TestNamespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      containers:
      - image: localhost:5001/stackit-git-base:6
        command: ["/usr/local/bin/gitea"]
        args: ["--config", "/data/app.ini", "web"]
        imagePullPolicy: IfNotPresent
        name: forgejo
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
 `

	runnerConfigMap = `apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.ConfigName}}
  namespace: {{.TestNamespace}}
data:
  .runner: |
    {
      "WARNING": "This file is automatically generated by act-runner. Do not edit it manually unless you know what you are doing. Removing this file will cause act runner to re-register as a new runner.",
      "id": 2,
      "uuid": "bbbed033-ea94-4b44-a3c1-b4e347589a15",
      "name": "5c61760e58c5",
      "token": "{{.ForgejoToken}}",
      "address": "{{.ForgejoAddress}}",
      "labels": [
        "ubuntu-20.04:docker://node:20-bookworm"
      ]
    }
`

	scaledJob = `apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  labels:
    app: forgejo-runner
  name: forgejo-runner
  namespace: {{.TestNamespace}}
spec:
  jobTargetRef:
    template:
      metadata:
        labels:
          app: forgejo-job
      spec:
        volumes:
        - name: runner-data
          emptyDir: {}
        - name: runner-config
          configMap:
            name: {{.ConfigName}}
        containers:
        - name: runner
          image: data.forgejo.org/forgejo/runner:6.3.1
          command: ["sh", "-c", "forgejo-runner one-job"]
          volumeMounts:
          - name: runner-data
            mountPath: /data
          - name: runner-config
            mountPath: /config
            readOnly: false
  minReplicaCount: 0
  maxReplicaCount: 1
  pollingInterval: 5
  triggers:
  - type: forgejo-runner
    metadata:
      name: "{{.ForgejoRunnerName}}"
      token: "{{.ForgejoAccessToken}}"
      address: "{{.ForgejoAddress}}"
      global: "{{.ForgejoGlobal}}"
      labels: "{{.ForgejoLabel}}"
`
)

func TestForgejoScaler(t *testing.T) {
	// setting up
	t.Log("--- setting up ---")
	require.NotEmpty(t, forgejoToken, "FORGEJO_TOKEN env variable is required")
	require.NotEmpty(t, forgejoAccessToken, "FORGEJO_ACCESS_TOKEN env variable is required")

	kc := GetKubernetesClient(t)
	data, templates := getTemplateData()
	t.Cleanup(func() {
		DeleteKubernetesResources(t, testNamespace, data, templates)
	})

	// Create kubernetes resources
	CreateKubernetesResources(t, kc, testNamespace, data, templates)

	// setup forgejo
	setupForgejo(t, kc)

	// test scaling
	testScaleOut(t, kc)
	testScaleIn(t, kc)
}

func getTemplateData() (templateData, []Template) {
	return templateData{
			TestNamespace:      testNamespace,
			DeploymentName:     deploymentName,
			ScaledObjectName:   scaledJobName,
			ConfigName:         configName,
			ForgejoRunnerName:  forgejoRunnerName,
			ForgejoToken:       forgejoToken,
			ForgejoGlobal:      forgejoGlobal,
			ForgejoLabel:       forgejoLabel,
			ForgejoAccessToken: forgejoAccessToken,
			ForgejoAddress:     forgejoAddress,
		}, []Template{
			{Name: "runnerConfigMapTemplate", Config: runnerConfigMap},
			{Name: "forgejoDeploymentTemplate", Config: forgejoDeployment},
			{Name: "forgejoServiceTemplate", Config: forgejoService},
			{Name: "scaledObjectTemplate", Config: scaledJob},
		}
}

func setupForgejo(t *testing.T, kc *kubernetes.Clientset) {
	require.True(t,
		WaitForDeploymentReplicaReadyCount(t, kc, "forgejo", testNamespace, 1, 3, 20),
		"Forgejo should be running after 1 minute")
}

// pre-loaded database should scale automatically on label
func testScaleOut(t *testing.T, kc *kubernetes.Clientset) {
	t.Log("--- testing scale out ---")

	assert.True(t, WaitForPodCountInNamespace(t, kc, testNamespace, minReplicaCount, 60, 1), "pods count should be 2 after 1 minute")
}

func testScaleIn(t *testing.T, kc *kubernetes.Clientset) {
	t.Log("--- testing scale in ---")

	assert.True(t, WaitForPodCountInNamespace(t, kc, testNamespace, maxReplicaCount, 60, 1), "pods count should be 1 after 1 minute")
}
